name: flutter_pin_code_fields
description: A flutter package which will help you generate customizable pin code fields. Can be used for login pins or OTP.
version: 1.1.0
author: Sanif Himani <sanifhimani92@gmail.com>
homepage: https://github.com/sanifhimani/flutter_pin_code_fields

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
